title: Christopher Li # your name (or website title) here
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Master's in Statistics student at UC Davis and will graduate in December 2023. I am in interested applying statistical methods
  and machine learning models to answer interesrting research questions in healthcare, biology, and professional sports.
  <br><br>
  <a href="https://www.https://www.linkedin.com/in/christopher-li-571679112/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
